# Generated by Django 2.2.4 on 2019-12-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191215_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='密保问题文本')),
            ],
            options={
                'verbose_name': '密保问题',
                'verbose_name_plural': '密保问题',
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='authority',
        ),
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.CharField(default=1990, max_length=30, verbose_name='密保问题答案'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.PasswordQuestion', verbose_name='密保问题'),
            preserve_default=False,
        ),
    ]
