# Generated by Django 2.2.4 on 2019-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191220_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question',
        ),
    ]
