# Generated by Django 2.2.4 on 2019-12-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191220_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.CharField(default=1, max_length=30, verbose_name='密保问题答案'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.PasswordQuestion', verbose_name='密保问题'),
        ),
    ]
