# Generated by Django 2.2.4 on 2019-12-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('real_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (-1, '女')], default=1, verbose_name='性别')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='工号')),
                ('real_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (-1, '女')], default=1, verbose_name='性别')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程号')),
                ('name', models.CharField(max_length=20, verbose_name='课程名')),
                ('student', models.ManyToManyField(null=True, to='ems.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Teacher', verbose_name='任课教师')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Term', verbose_name='开课学期')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(verbose_name='分数')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Student', verbose_name='学生')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Subject', verbose_name='课程')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
            },
        ),
    ]
