# Generated by Django 2.2.4 on 2019-12-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_auto_20191215_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1111, max_length=10, verbose_name='校园卡密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1111, max_length=10, verbose_name='校园卡密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='ems.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='用户'),
        ),
    ]
