# Generated by Django 2.2.4 on 2019-12-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20191216_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.FloatField(default=1, verbose_name='学分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='用户'),
        ),
    ]
