# Generated by Django 2.2.4 on 2019-12-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_auto_20191216_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject')},
        ),
    ]
